version: '3'

services:
    agent:
        build: agent
        ports:
          - '8001-8099:830'
        environment:
          - CALLBACK_URL=http://${SERVER_IP}:${API_SERVER_PORT}/callback

networks:
    default:
        external:
            name: sdn_optical_network